AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Path Tracer App Stack

Globals:
  Function:
    Timeout: 900 # 15 minutes
    MemorySize: 2048

Resources:
  PathTraceFunction:
    Type: AWS::Serverless::Function
    Architectures:
        - x86_64
    Properties:
      PackageType: Image
      MemorySize: 2048
      Policies:
        - S3ReadPolicy:
            BucketName: "distributed-path-tracer"
        - S3WritePolicy:
            BucketName: "distributed-path-tracer"
        - LambdaInvokePolicy:
            FunctionName: !GetAtt PathTraceFunction.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Sub "arn:aws:sns:${REGION}:${AWS::AccountId}:*-distributed-scene-topic"
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !Sub "arn:aws:sqs:${REGION}:${AWS::AccountId}:*-distributed-scene-worker-*"
      Events:
        PathTrace:
          Type: Api 
          Properties:
            Path: /path-trace
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../path-tracer-core
      DockerTag: latest

Outputs:
  PathTraceFunction:
    Description: "Path Trace Lambda Function ARN"
    Value: !GetAtt PathTraceFunction.Arn
    Export:
      Name: PathTraceFunctionARN