AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Path Tracer Preprocessor Function
 
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Parameters:
  ENV:
    Type: String

Resources:
  PathTracerPreprocessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionName: "distributed-path-tracer-preprocessor"
      Policies:
        - S3ReadPolicy:
            BucketName: "distributed-path-tracer"
        - S3WritePolicy:
            BucketName: "distributed-path-tracer"
        - LambdaInvokePolicy:
            FunctionName: "distributed-path-tracer-worker"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:CreateTopic
                - sns:Subscribe
              Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*-distributed-scene-topic"
            - Effect: Allow
              Action:
                - sqs:CreateQueue
                - sqs:GetQueueAttributes
                - sqs:SetQueueAttributes
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*-distributed-scene-worker-*"
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          ENV: !Ref ENV
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../path-tracer-preprocessor/preprocessor-function
      DockerTag: latest

Outputs:
  PathTracerPreprocessorFunction:
    Description: "Path Tracer Preprocessor Lambda Function ARN"
    Value: !GetAtt PathTracerPreprocessorFunction.Arn