AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Path Tracer Preprocessor Function
 
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  PathTracerPreprocessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Preprocess:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /preprocess
            Method: get
      Environment:
        Variables:
          PathTraceFunctionARN: !GetAtt PathTraceFunction.Arn
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../path-tracer-preprocessor/preprocessor-function
      DockerTag: latest

Outputs:
  PathTracerPreprocessorFunction:
    Description: "Path Tracer Preprocessor Lambda Function ARN"
    Value: !GetAtt PathTracerPreprocessorFunction.Arn
  PathTracerPreprocessorFunctionIamRole:
    Description: "Implicit IAM Role created for Path Tracer PreprocessorFunction function"
    Value: !GetAtt PathTracerPreprocessorFunction.Arn
